#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#  AaharAI NutriSync — One-Command Bootstrap Script
#  Works on: Linux, macOS
#  Usage: bash setup.sh
# ═══════════════════════════════════════════════════════════════
set -e

# ── Colors ──────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}ℹ  $*${RESET}"; }
success() { echo -e "${GREEN}✅ $*${RESET}"; }
warn()    { echo -e "${YELLOW}⚠  $*${RESET}"; }
error()   { echo -e "${RED}❌ $*${RESET}"; exit 1; }
step()    { echo -e "\n${BOLD}── $* ──────────────────────────────${RESET}"; }

# ── Header ──────────────────────────────────────────────────────
echo ""
echo -e "${CYAN}${BOLD}"
echo "  ╔═══════════════════════════════════════╗"
echo "  ║     AaharAI NutriSync Setup           ║"
echo "  ║   AI-powered Indian Nutrition          ║"
echo "  ╚═══════════════════════════════════════╝"
echo -e "${RESET}"

# ── Tool Checks ──────────────────────────────────────────────────
step "Checking Prerequisites"
command -v python3 >/dev/null 2>&1 || error "Python 3.11+ is required. Install from https://python.org"
command -v node   >/dev/null 2>&1 || error "Node.js 18+ is required. Install from https://nodejs.org"
command -v npm    >/dev/null 2>&1 || error "npm is required. Install from https://nodejs.org"

PYTHON_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
NODE_VERSION=$(node --version | sed 's/v//')
info "Python: $PYTHON_VERSION | Node: $NODE_VERSION"

# Check Python 3.11+
python3 -c "import sys; exit(0 if sys.version_info >= (3,11) else 1)" || \
  warn "Python 3.11+ recommended. Current: $PYTHON_VERSION"

success "Prerequisites OK"

# ── Backend Setup ─────────────────────────────────────────────────
step "Setting Up Python Backend"

cd backend

# Virtual environment
if [ ! -d "venv" ]; then
    info "Creating virtual environment..."
    python3 -m venv venv
    success "Virtual environment created"
else
    info "Virtual environment already exists"
fi

# Activate
source venv/bin/activate

# Upgrade pip
pip install --upgrade pip --quiet

# Install dependencies
info "Installing Python dependencies (this may take 2-3 minutes)..."
pip install -r requirements.txt --quiet
success "Python dependencies installed"

# ── Environment Variables ─────────────────────────────────────────
step "Configuring Environment"

if [ ! -f ".env" ]; then
    if [ -f "../.env.example" ]; then
        cp ../.env.example .env
        # Generate a secure SECRET_KEY
        SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_hex(32))')
        # Replace placeholder
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s/SECRET_KEY=.*/SECRET_KEY=${SECRET_KEY}/" .env
        else
            sed -i "s/SECRET_KEY=.*/SECRET_KEY=${SECRET_KEY}/" .env
        fi
        success "Created backend/.env with auto-generated SECRET_KEY"
        warn "IMPORTANT: Edit backend/.env to add your API keys (Groq, etc.)"
    else
        # Create minimal .env
        cat > .env << EOF
# Auto-generated by setup.sh
SECRET_KEY=$(python3 -c 'import secrets; print(secrets.token_hex(32))')
DATABASE_URL=
OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_MODEL=gemma3:4b
OLLAMA_EMBED_MODEL=nomic-embed-text
GROQ_API_KEY=
GROQ_MODEL=llama-3.3-70b-versatile
DEBUG=false
EOF
        success "Created minimal backend/.env"
        warn "Add GROQ_API_KEY in backend/.env for cloud AI fallback"
    fi
else
    info "backend/.env already exists — skipping"
fi

# ── Database Initialization ───────────────────────────────────────
step "Initializing Database"
python3 -c "from app.models.user import init_db; init_db(); print('Database tables created')"
success "SQLite database initialized"

# ── RAG Check ────────────────────────────────────────────────────
step "Checking Vector Database"
CHROMA_PATH="app/db/static/chroma_db"
EXCEL_PATH="app/db/static/AaharAI_NutriSync_Enhanced.xlsx"

if [ -d "$CHROMA_PATH" ] && [ "$(ls -A $CHROMA_PATH 2>/dev/null)" ]; then
    success "ChromaDB already populated — skipping ingestion"
elif [ -f "$EXCEL_PATH" ]; then
    info "Running RAG ingestion pipeline (this takes 3-10 minutes)..."
    python3 -m app.services.rag.ingest
    success "ChromaDB populated with knowledge base"
else
    warn "Excel data file not found at $EXCEL_PATH"
    warn "Chat AI will run without RAG knowledge base"
    warn "Add the data file and run: make ingest"
fi

cd ..

# ── Frontend Setup ────────────────────────────────────────────────
step "Setting Up Node.js Frontend"

cd frontend

if [ ! -d "node_modules" ]; then
    info "Installing Node.js dependencies..."
    npm install --silent
    success "Frontend dependencies installed"
else
    info "node_modules already exists — running npm install to verify..."
    npm install --silent
fi

# Frontend environment
if [ ! -f ".env.local" ]; then
    echo "NEXT_PUBLIC_API_URL=http://localhost:8000" > .env.local
    success "Created frontend/.env.local"
else
    info "frontend/.env.local already exists"
fi

cd ..

# ── Ollama Suggestion ─────────────────────────────────────────────
step "Checking Local AI (Ollama)"
if command -v ollama >/dev/null 2>&1; then
    success "Ollama is installed"
    if curl -sf http://localhost:11434/api/tags > /dev/null 2>&1; then
        success "Ollama is running"
    else
        warn "Ollama not running. Start it with: ollama serve"
        info "Then pull models with:"
        info "  ollama pull gemma3:4b"
        info "  ollama pull nomic-embed-text"
    fi
else
    warn "Ollama not installed (optional for local AI)"
    info "Install from: https://ollama.ai"
    info "Or use a cloud provider (Groq, OpenAI) from Settings"
fi

# ── Final Instructions ────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}"
echo "  ╔════════════════════════════════════════════╗"
echo "  ║          Setup Complete! 🎉                ║"
echo "  ╚════════════════════════════════════════════╝"
echo -e "${RESET}"
echo ""
echo -e "  ${BOLD}To start the application:${RESET}"
echo ""
echo -e "    ${CYAN}make run${RESET}                    # Start both together"
echo ""
echo -e "    ${CYAN}make run-backend${RESET}            # Backend only"
echo -e "    ${CYAN}make run-frontend${RESET}           # Frontend only"
echo ""
echo -e "  ${BOLD}URLs:${RESET}"
echo -e "    Frontend : ${CYAN}http://localhost:3001${RESET}"
echo -e "    Backend  : ${CYAN}http://localhost:8000${RESET}"
echo -e "    API Docs : ${CYAN}http://localhost:8000/docs${RESET}"
echo ""
echo -e "  ${YELLOW}Tip: Add your Groq API key in backend/.env for fast cloud AI${RESET}"
echo ""
